### ISSUE TITLE
Improve the warning email message

### ISSUE THREAD

**Issue by brendanheywood** [sebsoftnl/moodle-tool_usersuspension#1]
Assume smartdetect_suspendafter = 12 weeks and smartdetect_warninginterval = 2 weeks, the message says:

"To prevent this from occuring, log into the system in the next 12 weeks"

This is not quite correct and is slightly ambigous. A better message might be something like:

"You must login within the next 2 weeks to keep your account active. To prevent this from occurring ongoing ensure you log into the system at least every 12 weeks"

**Comment by rogiervandongen** [comment]
Dear Brendan,
I suspect this is running on one of the forks at Catalyst IT because this configuration value and message is not on our branch.
Regarding that, it would be more than just appreciated if those forks would actually be turned into pull requests.
After all, this is open source and the plugin is available from Moodle.org.
It would be much appreciated if the community can actually benefit from changes made by parties who fork the plugin, especially when they have a commercial mindset.
This is not just the case for the Moodle branch(es), but also for the Totara branch(es).

Cheers,
Rogier

**Comment by rogiervandongen** [comment]
Addendum: The added Totara specifics are in the process of being backmerged to our master branch, with the provided issue being resolved according to your request.

My advice is, for now, to wait for the new version to be available here and see if or how you merge this into the Totara-12 branch at Catalyst IT. Substantial changes are to be pushed soon, so it may be easier to merge on the side of catalyst.

Please do note that it would still be much appreciated if any substantial changes, be it on a Totara specific branch or any other branch, are being pushed back to us by means of a PR.

Cheers again,
Rogier

**Comment by rogiervandongen** [comment]
Resolved.
See https://github.com/sebsoftnl/moodle-tool_usersuspension/releases/tag/3.5.7

**Comment by brendanheywood** [comment]
hi @rogiervandongen - sorry if we missed some PRs we do try to keep on top of those and contribute back as much we can

**Comment by rogiervandongen** [comment]
@brendanheywood no worries.
If you get the time somewhere (I know you guys are pretty busy and maintain a lot of plugins) and the Totara branch has been updated for the latest changes, please do consider filing a PR.
I *may* be able to do this myself but considering the workload here too, it could well be that you guys may have synced the latest changes to the Totara12 branch before I do.
Thanks again though & cheers :)
